bottom_up_tree_node:
  ros__parameters:
    init_delay: 1.5
    robot_closeness_threshold: 0.35 #minimum approach distance of the robot, we do not want to hit subject TODO: test optimum
    target_reached_threshold: 1.5  # the critical distance of target and subject to tell if reached TODO: test optimum

    visibility_time_threshold: 2 # time threshold of last incoming 'subject' data
    robot_approach_distance : 1.0 #how much the robot should go at once in dog condition TODO: test optimum
    Dog_following_max_threshold: 2.0 # maximum distance difference allowed from the robot to still consider following 
    Dog_max_wander_allowed: 2 # maximum allowed wander count before considering the subject lost

    Dog_checkpoints:
     - "{'X':0.687003, 'Y':3.54149, 'Z':0.0 }"
     - "{'X':-3.06462, 'Y':5.40894, 'Z':0.0 }"
     - "{'X':-4.28269, 'Y':1.40561, 'Z':0.0 }"
     - "{'X':-0.033288, 'Y':-0.398331, 'Z':0.0 }"
     - "{'X':0.417255, 'Y':-0.539768, 'Z':0.0 }"
      # Régi
      #- "{'X':0.667161, 'Y':3.67737, 'Z':0.0 }"
      #- "{'X':-0.75722, 'Y':3.50665, 'Z':0.0 }"
      #- "{'X':-2.21907, 'Y':4.21585, 'Z':0.0 }"
      #- "{'X':-3.06938, 'Y':5.11237, 'Z':0.0 }"
      #- "{'X':-3.45608, 'Y':2.35092, 'Z':0.0 }"
      #- "{'X':-3.88019, 'Y':0.850578, 'Z':0.0 }"
      #- "{'X':-0.735457, 'Y':0.0260696, 'Z':0.0 }"
      #- "{'X':-0.160881, 'Y':-0.149748, 'Z':0.0 }"
      #- "{'X':0.176912, 'Y':-0.235893, 'Z':0.0 }"
      #- "{'X':0.248956, 'Y':-0.291555, 'Z':0.0 }"
      #Folyosó
      #- "{'X':8.71365, 'Y':20.043, 'Z':0.0 }"
      #- "{'X':8.519, 'Y':18.0837, 'Z':0.0 }"
      #- "{'X':9.35348, 'Y':17.5724, 'Z':0.0 }"
      #- "{'X':2.71861, 'Y':16.8758, 'Z':0.0 }"
      #- "{'X':1.89235, 'Y':20.1364, 'Z':0.0 }"
      #- "{'X':2.0025, 'Y':18.715, 'Z':0.0 }"
      #- "{'X':1.80331, 'Y':19.9152, 'Z':0.0 }"
      #- "{'X':1.64292, 'Y':20.8728, 'Z':0.0 }"
      
    LED_start_setting: 
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}"

    LED_indicate_target_seq:
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':6, 'color':1},'fr':{'mode':6, 'color':1},'bl':{'mode':6, 'color':1},'br':{'mode':6, 'color':1}}" #white slow blink
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':6, 'color':1},'fr':{'mode':6, 'color':1},'bl':{'mode':6, 'color':1},'br':{'mode':6, 'color':1}}" #white slow blink
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
     
    LED_indicate_target_times:
      - 1 #black
      - 3 #white
      - 1 #black
      - 3 #white
      - 1 #black
      - 3 #white
      - 1 #black

    LED_indicate_close_target_seq:
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':5, 'color':2},'fr':{'mode':5, 'color':2},'bl':{'mode':5, 'color':2},'br':{'mode':5, 'color':2}}" # yellow fast blink
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':5, 'color':2},'fr':{'mode':5, 'color':2},'bl':{'mode':5, 'color':2},'br':{'mode':5, 'color':2}}" # yellow fast blink
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':5, 'color':2},'fr':{'mode':5, 'color':2},'bl':{'mode':5, 'color':2},'br':{'mode':5, 'color':2}}" # yellow fast blink
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':1, 'color':1},'br':{'mode':2, 'color':1}}" #black fix
      

    LED_indicate_close_target_times:
      - 1 #black
      - 3 #yellow
      - 1 #black
      - 3 #yellow
      - 1 #black
      - 3 #yellow
      - 1 #black

    LED_catch_attention_seq:
      - "{'fl':{'mode':6, 'color':1},'fr':{'mode':6, 'color':1},'bl':{'mode':6, 'color':1},'br':{'mode':6, 'color':1}}" #white slow blink
      - "{'fl':{'mode':4, 'color':0},'fr':{'mode':4, 'color':0},'bl':{'mode':4, 'color':0},'br':{'mode':4, 'color':0}}" #black fix
      - "{'fl':{'mode':6, 'color':1},'fr':{'mode':6, 'color':1},'bl':{'mode':6, 'color':1},'br':{'mode':6, 'color':1}}" #white slow blink
      - "{'fl':{'mode':1, 'color':1},'fr':{'mode':2, 'color':1},'bl':{'mode':2, 'color':1},'br':{'mode':1, 'color':1}}" #black fix
    
    LED_catch_attention_times:
        - 1.5 #white
        - 0.5 #black
        - 1.5 #white
        - 0.5 #black

    Dog_indicate_target_seq:
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':3.19,'gr_pos':7.05}" #gripper open, look ahead
       - "{'n_pos':8.5,'gl_pos':7.05,'gr_pos':3.19}" #gripper close, look ahead
       - "{'n_pos':8.5,'gl_pos':6.83,'gr_pos':3.36}" #gripper to default, look ahead
  
    Dog_indicate_target_times:
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5

    Dog_catch_attention_seq:
       - "{'n_pos':8.90,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look up
       - "{'n_pos':8.50,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look ahead
       - "{'n_pos':8.90,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look up
       - "{'n_pos':8.50,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look ahead
       - "{'n_pos':8.90,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look ahead
       - "{'n_pos':8.50,'gl_pos':3.36,'gr_pos':6.83}" #gripper to default, look up
       
    
    Dog_catch_attention_times:
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
      
